name: Auto PR on Parent Repo Responder

on: [repository_dispatch]

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Checkout submodule
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.client_payload.repository }}
          repository: hid-gs/${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.sha }}
        if: github.event.action == 'apop-pr-merged'
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}' commit '${{ github.event.client_payload.sha }}'"
      - name: APOP Create PR
        if: github.event.action == 'apop-pr-merged'
        run: |
          env | sort; \
          ls -la; \
          cd ${{ github.event.client_payload.repository }}; \
          git fetch --all; \
          git log; \
          cd ..; \
          git add ${{ github.event.client_payload.repository }}; \
          git commit -m "Auto update ${{ github.event.client_payload }} submodule"; \
          git push
