name: Auto PR on Parent Repo Responder

on: [repository_dispatch]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Always run
        run: |
          env | sort
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Checkout submodule
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.client_payload.repository }}
          repository: hid-gs/${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.sha }}
        if: github.event.action == 'apop-pr-merged'
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}' commit '${{ github.event.client_payload.sha }}'"
      - name: Check for pre-existing PR on same submodule
        run: |
          echo "check for pending PRs"
          git fetch --all
          git ls-remote
          git ls-remote | \
            awk '$0 ~ /refs\/pull\/[0-9]*\/merge/ {print $1}' | \
            while read hex; do \
              git show --name-stats $hex 2> /dev/null | \
              awk '$0 ~ /^[AMD]\t/ {print $2}'
            done
          echo "done"
      - name: APOP Create PR
        if: github.event.action == 'apop-pr-merged'
        run: |
          cd ${{ github.event.client_payload.repository }}; \
          git fetch --all; \
          git log; \
          cd ..; \
          git config --global user.name 'Github Automation'; \
          git config --global user.email 'webteam@hidglobal.com'; \
          git add ${{ github.event.client_payload.repository }}; \
          git commit --author 'Github Automation <webteam@hidglobal.com>' -m "Auto update ${{ github.event.client_payload.repository }} submodule"; 
          BRANCHNAME="${{ github.event.client_payload.repository }}__update__${GITHUB_SHA}"
          git checkout -b ${BRANCHNAME}; \
          git push -u origin ${BRANCHNAME}
      - name: Create PR
        uses: devops-infra/action-pull-request@v0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main
          title: Automated PR - ${{ github.event.client_payload.repository }} - ${{ github.event.client_payload.sha }}
          body: |
            ***Automated pull request***

            Origin Repository: ${{ github.event.client_payload.repository }}
            Origin Commit: ${{ github.event.client_payload.sha }}

