name: Auto PR on Parent Repo Responder

on: [repository_dispatch]

permissions:
  pull-requests: write
  repos: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Checkout submodule
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.client_payload.repository }}
          repository: hid-gs/${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.sha }}
        if: github.event.action == 'apop-pr-merged'
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}' commit '${{ github.event.client_payload.sha }}'"
      - name: APOP Create PR
        if: github.event.action == 'apop-pr-merged'
        run: |
          cd ${{ github.event.client_payload.repository }}; \
          git fetch --all; \
          git log; \
          cd ..; \
          git config --global user.name 'Github Automation'; \
          git config --global user.email 'webteam@hidglobal.com'; \
          git add ${{ github.event.client_payload.repository }}; \
          git commit --author 'Github Automation <webteam@hidglobal.com>' -m "Auto update ${{ github.event.client_payload }} submodule"; 
          BRANCHNAME="${{ github.event.client_payload.repository }}__update__${GITHUB_SHA}"
          git checkout -b ${BRANCHNAME}; \
          git push -u origin ${BRANCHNAME}
      - name: Create PR
        uses: devops-infra/action-pull-request@v0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main
          title: Automated PR
          body: "**Automated pull request**"

